### ISSUE TITLE
Using the log package in go

### ISSUE THREAD

**Issue by hiroyasuusami** [gohxs/cloudmount#1]
It looks like the log package has not been imported in go.

When installation,
$ go get github.com/gohxs/cloudmount
**The following error occurs.**
../go-workspace/src/github.com/gohxs/cloudmount/flags.go:39:4: undefined: log
../go-workspace/src/github.com/gohxs/cloudmount/flags.go:68:4: undefined: log
../go-workspace/src/github.com/gohxs/cloudmount/flags.go:74:3: undefined: log
../go-workspace/src/github.com/gohxs/cloudmount/flags.go:79:3: undefined: log

**Comment by hexasoftware** [comment]
This is odd, since log it should be a global variable that mimics the log package

https://github.com/gohxs/cloudmount/blob/master/main.go#L25

**Comment by hexasoftware** [comment]
It was fetching fine here in a blank environment, either way I removed the global var and added log package to flags
