### ISSUE TITLE
Dropbox: get available storage

### ISSUE THREAD

**Issue by dvershinin** [gohxs/cloudmount#4]
Listing of disk space usage with `df -h` yields the following:

    df: ‘/mnt’: Function not implemented
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/root       412G   20G  372G   5% /
    ...

Expected: Dropbox storage appears alongside other filesystem and shows used / available storage.

**Comment by stdiopt** [comment]
I implemented file system stat for dropbox and gdrive focusing on individual quotas (not on team quotas)
